# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Files/GUI_FFT_LSTM_Stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
sys.path.append("APP/Pakages/DataSetgenPacks")
sys.path.append("APP/Pakages/ForcastingPacks")
sys.path.append("APP/Pakages/Seed_Model")
#from Trainer_Predicting_Esamble import Model_Trainer
#from Forcaster_Model import Forcast_Data
#from Forcaster_Model_DateFromToForcast import Forcast_Data


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

import pandas as pd
import numpy as np

from Model_Trainner import DL_Trainner
from Model_Creator import DL_Model
from DataSet_Creator import DL_DataSet

#To see easy the db file is to drag bdfiel into:  https://inloop.github.io/sqlite-viewer/
#or by using the command c.execute('SELECT * FROM estudiantes")
#print (c.fetchall()) a list is generated


class Ui_GUI_LSTM_FORCASTER(object):
    def __init__(self):
        #### PathFiles  ####
        
        ####  App Instances 
        #Opening connection
        self.Forcaster_DB_conn=sqlite3.connect('APP/DataStructures/Predict_model.db')
        #Create cursor
        self.Forcaster_DB_c = self.Forcaster_DB_conn.cursor()
        
        ### Classes 
        # Trainnign room
        self.trainner = DL_Trainner()
        # Model Creator
        self.model_creator = DL_Model() 
        # DataSet creator
        self.DataSet_creator = DL_DataSet() 
        
        ## global var init
        
        self.GetSeedDataModel()

        self.GetModelTable()
                
        self.GetSeed_DataSet()
        
        self.GetDataSetTable()
        
        
    
    def setupUi(self, GUI_LSTM_FORCASTER):
        GUI_LSTM_FORCASTER.setObjectName("GUI_LSTM_FORCASTER")
        GUI_LSTM_FORCASTER.resize(700, 446)
        self.centralwidget = QtWidgets.QWidget(GUI_LSTM_FORCASTER)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 0, 681, 421))
        self.Tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setMovable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.BasicConf_Tab = QtWidgets.QWidget()
        self.BasicConf_Tab.setObjectName("BasicConf_Tab")
        self.BaCon_lbl_ChooseModel = QtWidgets.QLabel(self.BasicConf_Tab)
        self.BaCon_lbl_ChooseModel.setGeometry(QtCore.QRect(28, 50, 161, 20))
        self.BaCon_lbl_ChooseModel.setObjectName("BaCon_lbl_ChooseModel")
        self.BaCon_lbl_DatasetBelongs = QtWidgets.QLabel(self.BasicConf_Tab)
        self.BaCon_lbl_DatasetBelongs.setGeometry(QtCore.QRect(30, 130, 231, 16))
        self.BaCon_lbl_DatasetBelongs.setObjectName("BaCon_lbl_DatasetBelongs")
        self.BaCon_btn_SetConfig = QtWidgets.QPushButton(self.BasicConf_Tab)
        self.BaCon_btn_SetConfig.setGeometry(QtCore.QRect(520, 190, 113, 32))
        self.BaCon_btn_SetConfig.setObjectName("BaCon_btn_SetConfig")
        self.BaCon_Combox_ChooseModel = QtWidgets.QComboBox(self.BasicConf_Tab)
        self.BaCon_Combox_ChooseModel.setGeometry(QtCore.QRect(26, 70, 361, 26))
        self.BaCon_Combox_ChooseModel.setObjectName("BaCon_Combox_ChooseModel")
        self.BaCon_txtLine_DatasetBelongs = QtWidgets.QLineEdit(self.BasicConf_Tab)
        self.BaCon_txtLine_DatasetBelongs.setGeometry(QtCore.QRect(30, 150, 351, 21))
        self.BaCon_txtLine_DatasetBelongs.setObjectName("BaCon_txtLine_DatasetBelongs")
        self.Tabs.addTab(self.BasicConf_Tab, "")
        self.Forcasting_Tab = QtWidgets.QWidget()
        self.Forcasting_Tab.setObjectName("Forcasting_Tab")
        self.ForC_Loadbar_Forcast = QtWidgets.QProgressBar(self.Forcasting_Tab)
        self.ForC_Loadbar_Forcast.setGeometry(QtCore.QRect(140, 240, 391, 61))
        self.ForC_Loadbar_Forcast.setProperty("value", 24)
        self.ForC_Loadbar_Forcast.setObjectName("ForC_Loadbar_Forcast")
        self.ForC_ComBox_DateFrom = QtWidgets.QComboBox(self.Forcasting_Tab)
        self.ForC_ComBox_DateFrom.setGeometry(QtCore.QRect(50, 50, 221, 26))
        self.ForC_ComBox_DateFrom.setObjectName("ForC_ComBox_DateFrom")
        self.ForC_lbl_DateFrom = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_DateFrom.setGeometry(QtCore.QRect(50, 30, 60, 16))
        self.ForC_lbl_DateFrom.setObjectName("ForC_lbl_DateFrom")
        self.ForC_btn_StartForcasting = QtWidgets.QPushButton(self.Forcasting_Tab)
        self.ForC_btn_StartForcasting.setGeometry(QtCore.QRect(350, 110, 221, 101))
        self.ForC_btn_StartForcasting.setObjectName("ForC_btn_StartForcasting")
        self.ForC_radioButton_GetGraph = QtWidgets.QRadioButton(self.Forcasting_Tab)
        self.ForC_radioButton_GetGraph.setGeometry(QtCore.QRect(370, 50, 111, 20))
        self.ForC_radioButton_GetGraph.setObjectName("ForC_radioButton_GetGraph")
        self.label_6 = QtWidgets.QLabel(self.Forcasting_Tab)
        self.label_6.setGeometry(QtCore.QRect(140, 230, 171, 16))
        self.label_6.setObjectName("label_6")
        self.ForC_Gbox_ForcastResul = QtWidgets.QGroupBox(self.Forcasting_Tab)
        self.ForC_Gbox_ForcastResul.setGeometry(QtCore.QRect(50, 110, 251, 91))
        self.ForC_Gbox_ForcastResul.setObjectName("ForC_Gbox_ForcastResul")
        self.label_13 = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_5.setObjectName("label_5")
        self.ForC_lbl_TodayPrice = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.ForC_lbl_TodayPrice.setGeometry(QtCore.QRect(130, 31, 121, 16))
        self.ForC_lbl_TodayPrice.setObjectName("ForC_lbl_TodayPrice")
        self.ForC_lbl_TomorrowPrice = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.ForC_lbl_TomorrowPrice.setGeometry(QtCore.QRect(130, 61, 101, 16))
        self.ForC_lbl_TomorrowPrice.setObjectName("ForC_lbl_TomorrowPrice")
        self.ForC_txtLine_TailBackDays = QtWidgets.QLineEdit(self.Forcasting_Tab)
        self.ForC_txtLine_TailBackDays.setGeometry(QtCore.QRect(490, 50, 113, 21))
        self.ForC_txtLine_TailBackDays.setObjectName("ForC_txtLine_TailBackDays")
        self.ForC_lbl_TailBackDays = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_TailBackDays.setGeometry(QtCore.QRect(370, 30, 121, 16))
        self.ForC_lbl_TailBackDays.setObjectName("ForC_lbl_TailBackDays")
        self.ForC_lbl_or = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_or.setGeometry(QtCore.QRect(320, 53, 21, 16))
        self.ForC_lbl_or.setObjectName("ForC_lbl_or")
        self.Tabs.addTab(self.Forcasting_Tab, "")
        self.Model_Trainner_Tab = QtWidgets.QWidget()
        self.Model_Trainner_Tab.setObjectName("Model_Trainner_Tab")
        self.MoTr_lbl_chooseModel = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_chooseModel.setGeometry(QtCore.QRect(70, 30, 111, 16))
        self.MoTr_lbl_chooseModel.setObjectName("MoTr_lbl_chooseModel")
        self.MoTr_lbl_DataSet = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_DataSet.setGeometry(QtCore.QRect(70, 80, 60, 16))
        self.MoTr_lbl_DataSet.setObjectName("MoTr_lbl_DataSet")
        self.MoTr_btn_Totrain = QtWidgets.QPushButton(self.Model_Trainner_Tab)
        self.MoTr_btn_Totrain.setGeometry(QtCore.QRect(470, 30, 141, 51))
        self.MoTr_btn_Totrain.setObjectName("MoTr_btn_Totrain")
        self.MoTr_LoadBar_CMDTraining = QtWidgets.QProgressBar(self.Model_Trainner_Tab)
        self.MoTr_LoadBar_CMDTraining.setGeometry(QtCore.QRect(120, 250, 411, 41))
        self.MoTr_LoadBar_CMDTraining.setProperty("value", 0)
        self.MoTr_LoadBar_CMDTraining.setObjectName("MoTr_LoadBar_CMDTraining")
        self.MoTr_lbl_CMD_training = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_CMD_training.setGeometry(QtCore.QRect(120, 230, 370, 16))
        self.MoTr_lbl_CMD_training.setObjectName("MoTr_lbl_CMD_training")
        self.MoTr_txtLine_PercentDataSet = QtWidgets.QLineEdit(self.Model_Trainner_Tab)
        self.MoTr_txtLine_PercentDataSet.setGeometry(QtCore.QRect(70, 150, 61, 21))
        self.MoTr_txtLine_PercentDataSet.setObjectName("MoTr_txtLine_PercentDataSet")
        self.MoTr_lbl_PercentDataset = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_PercentDataset.setGeometry(QtCore.QRect(70, 130, 111, 16))
        self.MoTr_lbl_PercentDataset.setObjectName("MoTr_lbl_PercentDataset")
        self.MoTr_ComBox_ChooseModel = QtWidgets.QComboBox(self.Model_Trainner_Tab)
        self.MoTr_ComBox_ChooseModel.setGeometry(QtCore.QRect(70, 50, 111, 26))
        self.MoTr_ComBox_ChooseModel.setObjectName("MoTr_ComBox_ChooseModel")
        
        
        
        self.MoTr_btn_Cancel_train = QtWidgets.QPushButton(self.Model_Trainner_Tab)
        self.MoTr_btn_Cancel_train.setGeometry(QtCore.QRect(470, 90, 141, 51))
        self.MoTr_btn_Cancel_train.setObjectName("MoTr_btn_Cancel_train")
        self.MoTr_ComBox_Column_T_Predict = QtWidgets.QComboBox(self.Model_Trainner_Tab)
        self.MoTr_ComBox_Column_T_Predict.setGeometry(QtCore.QRect(270, 50, 81, 26))
        self.MoTr_ComBox_Column_T_Predict.setObjectName("MoTr_ComBox_Column_T_Predict")
        self.MoTr_ComBox_Column_T_Predict.addItem("")
        self.MoTr_ComBox_Column_T_Predict.addItem("")
        self.MoTr_ComBox_Column_T_Predict.addItem("")
        self.MoTr_ComBox_Column_T_Predict.addItem("")
        self.MoTr_ComBox_Column_T_Predict.addItem("")
        self.MoTr_lbl_ColumnPredict = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_ColumnPredict.setGeometry(QtCore.QRect(270, 30, 111, 16))
        self.MoTr_lbl_ColumnPredict.setObjectName("MoTr_lbl_ColumnPredict")
        self.MoTr_txtLine_ephocs = QtWidgets.QLineEdit(self.Model_Trainner_Tab)
        self.MoTr_txtLine_ephocs.setGeometry(QtCore.QRect(270, 100, 81, 21))
        self.MoTr_txtLine_ephocs.setObjectName("MoTr_txtLine_ephocs")
        self.MoTr_lbl_DataSet_2 = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_DataSet_2.setGeometry(QtCore.QRect(270, 80, 60, 16))
        self.MoTr_lbl_DataSet_2.setObjectName("MoTr_lbl_DataSet_2")
        self.MoTr_ComBox_DataSet = QtWidgets.QComboBox(self.Model_Trainner_Tab)
        self.MoTr_ComBox_DataSet.setGeometry(QtCore.QRect(70, 100, 111, 26))
        self.MoTr_ComBox_DataSet.setObjectName("MoTr_ComBox_DataSet")
        self.Tabs.addTab(self.Model_Trainner_Tab, "")
        self.Data_Manager_tab = QtWidgets.QWidget()
        self.Data_Manager_tab.setObjectName("Data_Manager_tab")
        self.DaMa_lbl_Seed_DataSet = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_Seed_DataSet.setGeometry(QtCore.QRect(60, 20, 201, 16))
        self.DaMa_lbl_Seed_DataSet.setObjectName("DaMa_lbl_Seed_DataSet")
        self.DaMa_btn_Update = QtWidgets.QPushButton(self.Data_Manager_tab)
        self.DaMa_btn_Update.setGeometry(QtCore.QRect(500, 200, 113, 101))
        self.DaMa_btn_Update.setObjectName("DaMa_btn_Update")
        self.DaMa_LoadBar_Progres = QtWidgets.QProgressBar(self.Data_Manager_tab)
        self.DaMa_LoadBar_Progres.setGeometry(QtCore.QRect(150, 340, 411, 41))
        self.DaMa_LoadBar_Progres.setProperty("value", 24)
        self.DaMa_LoadBar_Progres.setObjectName("DaMa_LoadBar_Progres")
        self.DaMa_LoadBar_Progres.setProperty("value",0)
        self.DaMa_Lbl_Progres = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_Lbl_Progres.setGeometry(QtCore.QRect(150, 330, 291, 16))
        self.DaMa_Lbl_Progres.setObjectName("DaMa_Lbl_Progres")
        self.DaMa_lbl_DataSetId = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_DataSetId.setGeometry(QtCore.QRect(370, 20, 91, 16))
        self.DaMa_lbl_DataSetId.setObjectName("DaMa_lbl_DataSetId")    
        self.DaMa_btn_Create = QtWidgets.QPushButton(self.Data_Manager_tab)
        self.DaMa_btn_Create.setGeometry(QtCore.QRect(370, 200, 113, 101))
        self.DaMa_btn_Create.setObjectName("DaMa_btn_Create")
        self.DaMa_txtLine_Stock_Item = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_Stock_Item.setGeometry(QtCore.QRect(60, 90, 231, 21))
        self.DaMa_txtLine_Stock_Item.setObjectName("DaMa_txtLine_Stock_Item")
        self.DaMa_txtLine_BackDay = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_BackDay.setGeometry(QtCore.QRect(60, 140, 80, 21))
        self.DaMa_txtLine_BackDay.setObjectName("DaMa_txtLine_BackDay")
        self.DaMa_txtLine_FFT_Frec = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_FFT_Frec.setGeometry(QtCore.QRect(210, 140, 80, 21))
        self.DaMa_txtLine_FFT_Frec.setObjectName("DaMa_txtLine_FFT_Frec")
        self.DaMa_lbl_Stock_Item = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_Stock_Item.setGeometry(QtCore.QRect(60, 70, 201, 16))
        self.DaMa_lbl_Stock_Item.setObjectName("DaMa_lbl_Stock_Item")
        self.DaMa_txtLine_DateTime = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_DateTime.setGeometry(QtCore.QRect(370, 90, 241, 21))
        self.DaMa_txtLine_DateTime.setObjectName("DaMa_txtLine_DateTime")
        self.DaMa_txtLine_DateTime.setEnabled(False)
        self.DaMa_txtLine_PathCSV_File = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_PathCSV_File.setGeometry(QtCore.QRect(370, 140, 241, 21))
        self.DaMa_txtLine_PathCSV_File.setObjectName("DaMa_txtLine_PathCSV_File")
        self.DaMa_lbl_DateTime = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_DateTime.setGeometry(QtCore.QRect(370, 70, 201, 16))
        self.DaMa_lbl_DateTime.setObjectName("DaMa_lbl_DateTime")
        self.DaMa_lbl_BackDays = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_BackDays.setGeometry(QtCore.QRect(60, 120, 80, 16))
        self.DaMa_lbl_BackDays.setObjectName("DaMa_lbl_BackDays")
        self.DaMa_lbl_FFT_Frec = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_FFT_Frec.setGeometry(QtCore.QRect(210, 120, 80, 16))
        self.DaMa_lbl_FFT_Frec.setObjectName("DaMa_lbl_FFT_Frec")
        self.DaMa_lbl_PathCSVFile = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_PathCSVFile.setGeometry(QtCore.QRect(370, 120, 201, 16))
        self.DaMa_lbl_PathCSVFile.setObjectName("DaMa_lbl_PathCSVFile")
        self.DaMa_CheckBox_Open = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Open.setGeometry(QtCore.QRect(40, 200, 100, 20))
        self.DaMa_CheckBox_Open.setObjectName("DaMa_CheckBox_Open")
        self.DaMa_lbl_Columns = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_Columns.setGeometry(QtCore.QRect(60, 180, 201, 16))
        self.DaMa_lbl_Columns.setObjectName("DaMa_lbl_Columns")
        self.DaMa_CheckBox_High = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_High.setGeometry(QtCore.QRect(40, 220, 100, 20))
        self.DaMa_CheckBox_High.setObjectName("DaMa_CheckBox_high")
        self.DaMa_CheckBox_Low = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Low.setGeometry(QtCore.QRect(40, 240, 100, 20))
        self.DaMa_CheckBox_Low.setObjectName("DaMa_CheckBox_Low")
        self.DaMa_CheckBox_Close = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Close.setGeometry(QtCore.QRect(40, 260, 100, 20))
        self.DaMa_CheckBox_Close.setObjectName("DaMa_CheckBox_Close")
        self.DaMa_CheckBox_DayNumber = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_DayNumber.setGeometry(QtCore.QRect(240, 200, 100, 20))
        self.DaMa_CheckBox_DayNumber.setObjectName("DaMa_CheckBox_DayNumber")
        self.DaMa_CheckBox_Open_FFT = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Open_FFT.setGeometry(QtCore.QRect(120, 200, 100, 20))
        self.DaMa_CheckBox_Open_FFT.setObjectName("DaMa_CheckBox_Open_FFT")
        self.DaMa_CheckBox_High_FFT = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_High_FFT.setGeometry(QtCore.QRect(120, 220, 100, 20))
        self.DaMa_CheckBox_High_FFT.setObjectName("DaMa_CheckBox_HighFFT")
        self.DaMa_CheckBox_Low_FFT = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Low_FFT.setGeometry(QtCore.QRect(120, 240, 100, 21))
        self.DaMa_CheckBox_Low_FFT.setObjectName("DaMa_CheckBox_Low_FFT")
        self.DaMa_CheckBox_Close_FFT = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Close_FFT.setGeometry(QtCore.QRect(120, 260, 100, 21))
        self.DaMa_CheckBox_Close_FFT.setObjectName("DaMa_CheckBox_Close_FFT")
        self.DaMa_CheckBox_Day_MonthNDay_C = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Day_MonthNDay_C.setGeometry(QtCore.QRect(240, 240, 100, 20))
        self.DaMa_CheckBox_Day_MonthNDay_C.setObjectName("DaMa_CheckBox_DayMonth")
        self.DaMa_CheckBox_Year = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Year.setGeometry(QtCore.QRect(240, 260, 100, 20))
        self.DaMa_CheckBox_Year.setObjectName("DaMa_CheckBox_Year")
        self.DaMa_CheckBox_Volume = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Volume.setGeometry(QtCore.QRect(40, 280, 100, 20))
        self.DaMa_CheckBox_Volume.setObjectName("DaMa_CheckBox_Volume")
        self.DaMa_CheckBox_Volume_FFT = QtWidgets.QCheckBox(self.Data_Manager_tab)
        self.DaMa_CheckBox_Volume_FFT.setGeometry(QtCore.QRect(120, 280, 100, 20))
        self.DaMa_CheckBox_Volume_FFT.setObjectName("DaMa_CheckBox_Volume_FFT")
        
        self.DaMa_ComBox_DataSet_Id = QtWidgets.QComboBox(self.Data_Manager_tab)
        self.DaMa_ComBox_DataSet_Id.setGeometry(QtCore.QRect(370, 40, 101, 26))
        self.DaMa_ComBox_DataSet_Id.setObjectName("DaMa_ComBox_DataSet_Id")
        self.DaMa_ComBox_DataSet_Id.clear() #When starting app, combobox is updated
        for i in self.DataSet_all: #ComboBox is updated
            Current_Row=i[0]
            self.DaMa_ComBox_DataSet_Id.addItem(str(Current_Row))
        
        self.DaMa_ComBox_Seed_DataSet = QtWidgets.QComboBox(self.Data_Manager_tab)
        self.DaMa_ComBox_Seed_DataSet.setGeometry(QtCore.QRect(60, 40, 101, 26))
        self.DaMa_ComBox_Seed_DataSet.setObjectName("DaMa_ComBox_Seed_DataSet")
        
        
        self.Tabs.addTab(self.Data_Manager_tab, "")
        
        self.ModCrtion = QtWidgets.QWidget()
        self.ModCrtion.setObjectName("ModCrtion")
        self.Model_C_LBL_Progres = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Progres.setGeometry(QtCore.QRect(160, 340, 450, 16))
        self.Model_C_LBL_Progres.setObjectName("Model_C_LBL_Progres")
        self.Model_C_LdBar = QtWidgets.QProgressBar(self.ModCrtion)
        self.Model_C_LdBar.setGeometry(QtCore.QRect(160, 350, 411, 41))
        self.Model_C_LdBar.setProperty("value", 0)
        self.Model_C_LdBar.setObjectName("Model_C_LdBar")
        self.Model_C_txtLine_LSTM1 = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_LSTM1.setGeometry(QtCore.QRect(20, 90, 270, 25))
        self.Model_C_txtLine_LSTM1.setObjectName("Model_C_txtLine_LSTM1")
        self.Model_C_txtLine_LSTM2 = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_LSTM2.setGeometry(QtCore.QRect(20, 150, 270, 25))
        self.Model_C_txtLine_LSTM2.setObjectName("Model_C_txtLine_LSTM2")
        self.Model_C_PB_Create_M = QtWidgets.QPushButton(self.ModCrtion)
        self.Model_C_PB_Create_M.setGeometry(QtCore.QRect(40, 260, 221, 71))
        self.Model_C_PB_Create_M.setObjectName("Model_C_PB_Create_M")
        self.Model_C_txtLine_Lyr_Dns = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_Lyr_Dns.setGeometry(QtCore.QRect(360, 30, 270, 25))
        self.Model_C_txtLine_Lyr_Dns.setObjectName("Model_C_txtLine_Lyr_Dns")
        self.Model_C_Lyr_Dn_Rgzr = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_Lyr_Dn_Rgzr.setGeometry(QtCore.QRect(360, 90, 270, 25))
        self.Model_C_Lyr_Dn_Rgzr.setObjectName("Model_C_Lyr_Dn_Rgzr")
        self.Model_C_txtLine_OptAdam_Co = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_OptAdam_Co.setGeometry(QtCore.QRect(360, 150, 270, 25))
        self.Model_C_txtLine_OptAdam_Co.setObjectName("Model_C_txtLine_OptAdam_Co")
        self.Model_C_txtLine_Colums = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_Colums.setGeometry(QtCore.QRect(360, 210, 270, 25))
        self.Model_C_txtLine_Colums.setObjectName("Model_C_txtLine_Colums")
        self.Model_C_txtLine_LryDCoeff = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_LryDCoeff.setGeometry(QtCore.QRect(20, 210, 270, 25))
        self.Model_C_txtLine_LryDCoeff.setObjectName("Model_C_txtLine_LryDCoeff")
        self.Model_C_LBL_LSTM1 = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_LSTM1.setGeometry(QtCore.QRect(20, 70, 180, 16))
        self.Model_C_LBL_LSTM1.setObjectName("Model_C_LBL_LSTM1")
        self.Model_C_LBL_LSTM2 = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_LSTM2.setGeometry(QtCore.QRect(20, 130, 180, 16))
        self.Model_C_LBL_LSTM2.setObjectName("Model_C_LBL_LSTM2")
        self.Model_C_LBL_LryDCoeff = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_LryDCoeff.setGeometry(QtCore.QRect(20, 190, 180, 16))
        self.Model_C_LBL_LryDCoeff.setObjectName("Model_C_LBL_LryDCoeff")
        self.Model_C_LBL_Lyr_Dns = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Lyr_Dns.setGeometry(QtCore.QRect(360, 10, 180, 16))
        self.Model_C_LBL_Lyr_Dns.setObjectName("Model_C_LBL_Lyr_Dns")
        self.Model_C_LBL_Lyr_Dn_Rgzr = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Lyr_Dn_Rgzr.setGeometry(QtCore.QRect(360, 70, 180, 16))
        self.Model_C_LBL_Lyr_Dn_Rgzr.setObjectName("Model_C_LBL_Lyr_Dn_Rgzr")
        self.Model_C_LBL_OptAdam_Co = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_OptAdam_Co.setGeometry(QtCore.QRect(360, 130, 180, 16))
        self.Model_C_LBL_OptAdam_Co.setObjectName("Model_C_LBL_OptAdam_Co")
        self.Model_C_LBL_Colums = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Colums.setGeometry(QtCore.QRect(360, 190, 180, 16))
        self.Model_C_LBL_Colums.setObjectName("Model_C_LBL_Colums")
        self.Model_C_LBL_BackDays = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_BackDays.setGeometry(QtCore.QRect(20, 10, 181, 16))
        self.Model_C_LBL_BackDays.setObjectName("Model_C_LBL_BackDays")
        self.Model_C_txtLine_BackDays = QtWidgets.QLineEdit(self.ModCrtion)
        self.Model_C_txtLine_BackDays.setGeometry(QtCore.QRect(20, 30, 131, 25))
        self.Model_C_txtLine_BackDays.setObjectName("Model_C_txtLine_LryDCoeff")
        self.Model_C_LBL_Int_Model = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Int_Model.setGeometry(QtCore.QRect(280, 260, 180, 16))
        self.Model_C_LBL_Int_Model.setObjectName("Model_C_LBL_Int_Model")
        self.Model_C_ComBox_Int_Model = QtWidgets.QComboBox(self.ModCrtion)
        self.Model_C_ComBox_Int_Model.setGeometry(QtCore.QRect(280, 280, 141, 25))
        self.Model_C_ComBox_Int_Model.setObjectName("Model_C_ComBox_Int_Model")
        
        self.Model_C_LBL_Int_Seed_Data = QtWidgets.QLabel(self.ModCrtion)
        self.Model_C_LBL_Int_Seed_Data.setGeometry(QtCore.QRect(195, 10, 180, 26))
        self.Model_C_LBL_Int_Seed_Data.setObjectName("Model_C_LBL_Int_Seed_Data")   
        self.Model_C_ComBox_Int_Seed_Data = QtWidgets.QComboBox(self.ModCrtion)
        self.Model_C_ComBox_Int_Seed_Data.setGeometry(QtCore.QRect(195, 30, 100, 26))
        self.Model_C_ComBox_Int_Seed_Data.setObjectName("Model_C_ComBox_Int_Seed_Data")
        self.Model_C_ComBox_Int_Seed_Data.clear() #When starting app, combobox is updated
        for i in self.SeedData_SLCT_all: #ComboBox is updated
            Current_Row=i[0]
            self.Model_C_ComBox_Int_Seed_Data.addItem(str(Current_Row))
        self.SeedDataComboBoxChanged() 
        
        self.Tabs.addTab(self.ModCrtion, "")
        
        
        GUI_LSTM_FORCASTER.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GUI_LSTM_FORCASTER)
        self.statusbar.setObjectName("statusbar")
        GUI_LSTM_FORCASTER.setStatusBar(self.statusbar)

        self.retranslateUi(GUI_LSTM_FORCASTER)
        self.Tabs.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(GUI_LSTM_FORCASTER)
        
        ### INIT Function calls
        self.UpdateLocalObjects()
        
        #----------- TAB MODEL TRAINNING  -------------
        ############ General Emit Signals
        self.MoTr_ComBox_ChooseModel.currentIndexChanged.connect(self.Model_To_Train_ComboBoxChanged)
        #self.Model_C_ComBox_Int_Model.currentIndexChanged.connect(self.ModelsComboBoxChanged)
        ############ Thread Emit Signals
        self.trainner.Update_TrainningProcssStatus.connect(self.Event_TrainningStatus)
        self.trainner.Update_Progress.connect(self.Event_UpdateProgress_TrainningProcess)
        self.trainner.Update_Progress_String.connect(self.Event_UpdateProgress_string_Trainning_Process)
        #####  Buttons calls ##### 
        self.MoTr_btn_Totrain.clicked.connect(self.Start_Trainning)
        self.MoTr_btn_Cancel_train.clicked.connect(self.Cancel_Trainning)
        
        
        #---------- TAB MODEL CREATOR  ------------
        ############ General Emit Signals
        self.Model_C_ComBox_Int_Seed_Data.currentIndexChanged.connect(self.SeedDataComboBoxChanged)
        self.Model_C_ComBox_Int_Model.currentIndexChanged.connect(self.ModelsComboBoxChanged)
        ############ Thread Emit Signals
        self.model_creator.Update_ModelCreationStatus.connect(self.Event_ModelCreationStatus)
        self.model_creator.Update_Progress.connect(self.Event_UpdateProgress_ModelCreator)
        self.model_creator.Update_Progress_String.connect(self.Event_UpdateProgress_string_ModelCreator)
        #####  Buttons calls ##### 
        self.Model_C_PB_Create_M.clicked.connect(self.Create_New_Model)
        
        
        #---------- TAB DATA MANAGEMENT  ------------
        ############ General Emit Signals
        self.DaMa_ComBox_Seed_DataSet.currentIndexChanged.connect(self.SeedDataSetComboBoxChanged)
        self.DaMa_ComBox_DataSet_Id.currentIndexChanged.connect(self.DataSetComboBoxChanged)
        
        ############ Thread Emit Signals
        self.DataSet_creator.Update_DataSetCreationStatus.connect(self.Event_DataSetCreationStatus)
        self.DataSet_creator.Update_Progress.connect(self.Event_UpdateProgress_DataSetCreator)
        self.DataSet_creator.Update_Progress_String.connect(self.Event_UpdateProgress_string_DataSetCreator)
        
        #####  Buttons calls #####   
        self.DaMa_btn_Create.clicked.connect(self.Create_DataSet)
        self.DaMa_btn_Update.clicked.connect(self.Update_DataSet)     
         
        

    def retranslateUi(self, GUI_LSTM_FORCASTER):
        _translate = QtCore.QCoreApplication.translate
        GUI_LSTM_FORCASTER.setWindowTitle(_translate("GUI_LSTM_FORCASTER", "Stock_Forcastig_Interface"))
        self.BaCon_lbl_ChooseModel.setText(_translate("GUI_LSTM_FORCASTER", "To choose the model"))
        self.BaCon_lbl_DatasetBelongs.setText(_translate("GUI_LSTM_FORCASTER", "Dataset that belongs to model"))
        self.BaCon_btn_SetConfig.setText(_translate("GUI_LSTM_FORCASTER", "Set Config"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.BasicConf_Tab), _translate("GUI_LSTM_FORCASTER", "Basic Config"))
        self.ForC_lbl_DateFrom.setText(_translate("GUI_LSTM_FORCASTER", "Date from"))
        self.ForC_btn_StartForcasting.setText(_translate("GUI_LSTM_FORCASTER", "START FORCASTING"))
        self.ForC_radioButton_GetGraph.setText(_translate("GUI_LSTM_FORCASTER", "Get the graph?"))
        self.label_6.setText(_translate("GUI_LSTM_FORCASTER", "Ready to forcast"))
        self.ForC_Gbox_ForcastResul.setTitle(_translate("GUI_LSTM_FORCASTER", "Forcast Result Close"))
        self.label_13.setText(_translate("GUI_LSTM_FORCASTER", "Today Close price:"))
        self.label_5.setText(_translate("GUI_LSTM_FORCASTER", "Tomorrow forcast:"))
        self.ForC_lbl_TodayPrice.setText(_translate("GUI_LSTM_FORCASTER", "2334"))
        self.ForC_lbl_TomorrowPrice.setText(_translate("GUI_LSTM_FORCASTER", "234"))
        self.ForC_txtLine_TailBackDays.setText(_translate("GUI_LSTM_FORCASTER", "200"))
        self.ForC_lbl_TailBackDays.setText(_translate("GUI_LSTM_FORCASTER", "Tail backdays"))
        self.ForC_lbl_or.setText(_translate("GUI_LSTM_FORCASTER", "Or"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Forcasting_Tab), _translate("GUI_LSTM_FORCASTER", "Forcasting"))
        self.MoTr_lbl_chooseModel.setText(_translate("GUI_LSTM_FORCASTER", "To choose Model"))
        self.MoTr_lbl_DataSet.setText(_translate("GUI_LSTM_FORCASTER", "DataSet"))
        self.MoTr_btn_Totrain.setText(_translate("GUI_LSTM_FORCASTER", "To train"))
        self.MoTr_lbl_CMD_training.setText(_translate("GUI_LSTM_FORCASTER", "CMD training process"))
        self.MoTr_txtLine_PercentDataSet.setText(_translate("GUI_LSTM_FORCASTER", "96"))
        self.MoTr_lbl_PercentDataset.setText(_translate("GUI_LSTM_FORCASTER", "% Data To used"))
        self.MoTr_btn_Cancel_train.setText(_translate("GUI_LSTM_FORCASTER", "Cancel"))
        self.MoTr_ComBox_Column_T_Predict.setItemText(0, _translate("GUI_LSTM_FORCASTER", "Open"))
        self.MoTr_ComBox_Column_T_Predict.setItemText(1, _translate("GUI_LSTM_FORCASTER", "High"))
        self.MoTr_ComBox_Column_T_Predict.setItemText(2, _translate("GUI_LSTM_FORCASTER", "Low"))
        self.MoTr_ComBox_Column_T_Predict.setItemText(3, _translate("GUI_LSTM_FORCASTER", "Close"))
        self.MoTr_ComBox_Column_T_Predict.setItemText(4, _translate("GUI_LSTM_FORCASTER", "Volume"))
        self.MoTr_lbl_ColumnPredict.setText(_translate("GUI_LSTM_FORCASTER", "Column to predict"))
        self.MoTr_txtLine_ephocs.setText(_translate("GUI_LSTM_FORCASTER", "50"))
        self.MoTr_lbl_DataSet_2.setText(_translate("GUI_LSTM_FORCASTER", "ephocs"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Model_Trainner_Tab), _translate("GUI_LSTM_FORCASTER", "Model Trainner"))
        self.DaMa_lbl_Seed_DataSet.setText(_translate("GUI_LSTM_FORCASTER", "Seed DataSet Id"))
        self.DaMa_btn_Update.setText(_translate("GUI_LSTM_FORCASTER", "Update"))
        self.DaMa_Lbl_Progres.setText(_translate("GUI_LSTM_FORCASTER", "Ready"))
        self.DaMa_lbl_DataSetId.setText(_translate("GUI_LSTM_FORCASTER", "DataSet id"))
        self.DaMa_btn_Create.setText(_translate("GUI_LSTM_FORCASTER", "Create"))
        self.DaMa_lbl_Stock_Item.setText(_translate("GUI_LSTM_FORCASTER", "Stock Item"))
        self.DaMa_lbl_DateTime.setText(_translate("GUI_LSTM_FORCASTER", "Date time"))
        self.DaMa_lbl_BackDays.setText(_translate("GUI_LSTM_FORCASTER", "BackDays"))
        self.DaMa_lbl_FFT_Frec.setText(_translate("GUI_LSTM_FORCASTER", "FFT_frec"))
        self.DaMa_lbl_PathCSVFile.setText(_translate("GUI_LSTM_FORCASTER", "Path CSV file"))
        self.DaMa_CheckBox_Open.setText(_translate("GUI_LSTM_FORCASTER", "Open"))
        self.DaMa_lbl_Columns.setText(_translate("GUI_LSTM_FORCASTER", "Columns"))
        self.DaMa_CheckBox_High.setText(_translate("GUI_LSTM_FORCASTER", "High"))
        self.DaMa_CheckBox_Low.setText(_translate("GUI_LSTM_FORCASTER", "Low"))
        self.DaMa_CheckBox_Close.setText(_translate("GUI_LSTM_FORCASTER", "Close"))
        self.DaMa_CheckBox_DayNumber.setText(_translate("GUI_LSTM_FORCASTER", "DayNumber"))
        self.DaMa_CheckBox_Open_FFT.setText(_translate("GUI_LSTM_FORCASTER", "Open FFT"))
        self.DaMa_CheckBox_High_FFT.setText(_translate("GUI_LSTM_FORCASTER", "High FFT"))
        self.DaMa_CheckBox_Low_FFT.setText(_translate("GUI_LSTM_FORCASTER", "Low FFT"))
        self.DaMa_CheckBox_Close_FFT.setText(_translate("GUI_LSTM_FORCASTER", "Close FFT"))
        self.DaMa_CheckBox_Day_MonthNDay_C.setText(_translate("GUI_LSTM_FORCASTER", "DayMonth"))
        self.DaMa_CheckBox_Year.setText(_translate("GUI_LSTM_FORCASTER", "Year"))
        self.DaMa_CheckBox_Volume.setText(_translate("GUI_LSTM_FORCASTER", "Volume"))
        self.DaMa_CheckBox_Volume_FFT.setText(_translate("GUI_LSTM_FORCASTER", "Volume FFT"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Data_Manager_tab), _translate("GUI_LSTM_FORCASTER", "Data manager"))
        self.Model_C_LBL_Progres.setText(_translate("GUI_LSTM_FORCASTER", "Ready"))
        self.Model_C_LdBar.setProperty("value",0)
        self.Model_C_PB_Create_M.setText(_translate("GUI_LSTM_FORCASTER", "Create model"))
        self.Model_C_LBL_Int_Seed_Data.setText(_translate("GUI_LSTM_FORCASTER", "#Int Seed_Data"))
        self.Model_C_LBL_LSTM1.setText(_translate("GUI_LSTM_FORCASTER", "LSTM_1_#Units"))
        self.Model_C_LBL_LSTM2.setText(_translate("GUI_LSTM_FORCASTER", "LSTM_2_#Units"))
        self.Model_C_LBL_LryDCoeff.setText(_translate("GUI_LSTM_FORCASTER", "Lyr_Drop_Coeff"))
        self.Model_C_LBL_Lyr_Dns.setText(_translate("GUI_LSTM_FORCASTER", "Lyr_Dns_#Unit"))
        self.Model_C_LBL_Lyr_Dn_Rgzr.setText(_translate("GUI_LSTM_FORCASTER", "Lyr_Dns_Rgzr_Coeff"))
        self.Model_C_LBL_OptAdam_Co.setText(_translate("GUI_LSTM_FORCASTER", "Optmzer_Adam_Coeff"))
        self.Model_C_LBL_Colums.setText(_translate("GUI_LSTM_FORCASTER", "Colums_N"))
        self.Model_C_LBL_Int_Model.setText(_translate("GUI_LSTM_FORCASTER", "#Int_model"))
        self.Model_C_LBL_BackDays.setText(_translate("GUI_LSTM_FORCASTER", "#BackDays"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ModCrtion), _translate("GUI_LSTM_FORCASTER", "Model Creation"))
        
    ###########################################
    #              Global Functions           #
    ###########################################
    def UpdateLocalObjects(self):
    
        #### Tranning tab
        self.TrainningTab_UpdateComboxModel_ID()
        self.TrainningTab_UpdateComboxDataSet_ID()
        
        #### Data Mananer Tab
        self.DataManagerTab_UpdateComboxDataSet_ID()
        self.DataManagerTab_UpdateComboxSeedDataSet_ID()
        
        ####   Model creator tab   ####
        self.ModelTab_UpdateComboBoxModel_ID()
    
    def GetModelTable(self):
        query="SELECT * FROM Models"
        self.Forcaster_DB_c.execute(query)
        self.ModelsData_SLCT_all=self.Forcaster_DB_c.fetchall()
        
    def GetDataSetTable(self):
        query="SELECT * FROM DataSet"
        self.Forcaster_DB_c.execute(query)
        self.DataSet_all=self.Forcaster_DB_c.fetchall()
        
    def GetSeedDataModel(self):
        query="SELECT * FROM Seed_Data" #This is seed model
        self.Forcaster_DB_c.execute(query)
        self.SeedData_SLCT_all=self.Forcaster_DB_c.fetchall()
        
    def GetSeed_DataSet(self):
        query="SELECT * FROM Seed_DataSet"
        self.Forcaster_DB_c.execute(query)
        self.SeedDataSet_all=self.Forcaster_DB_c.fetchall()
        
    
    
    ###########################################
    #              TAB Model Creator          #
    ###########################################
    
    ############### Bottons functions  ################
    
    def Create_New_Model(self):
        matching=False
        CurrentSeedDataRow=0
        BackDays=self.Model_C_txtLine_BackDays.text()
        LSTM1_Units=self.Model_C_txtLine_LSTM1.text()
        LSTM2_Units=self.Model_C_txtLine_LSTM2.text()
        LryDcoeff=self.Model_C_txtLine_LryDCoeff.text()
        Lyr_Dns=self.Model_C_txtLine_Lyr_Dns.text()
        Lyr_Dn_Rgzr=self.Model_C_Lyr_Dn_Rgzr.text()
        OptAdam_Co=self.Model_C_txtLine_OptAdam_Co.text()
        Colums=self.Model_C_txtLine_Colums.text()
        
        #Check if seed data already exist
        matching,matching_row=self.Check_Matching_DataSeed(Colums,LSTM1_Units,LSTM2_Units,LryDcoeff,Lyr_Dns,Lyr_Dn_Rgzr,OptAdam_Co,BackDays)
        
        #new seed data is created; if at least a feature has been changed
        if matching==False:
            self.Create_new_DataSeed_DB(Colums,LSTM1_Units,LSTM2_Units,LryDcoeff,Lyr_Dns,Lyr_Dn_Rgzr,OptAdam_Co,BackDays)
            query="SELECT * FROM Seed_Data WHERE Seed_Data_id=(SELECT max(Seed_Data_id) FROM Seed_Data)"
            self.Forcaster_DB_c.execute(query)
            ContentList=self.Forcaster_DB_c.fetchall()
            for i in ContentList: 
                CurrentSeedDataRow=i[0]
            #Adding to Combo Box the data seed just created
            self.AddinElementComoBoxDataSeed(CurrentSeedDataRow)
        else:
            CurrentSeedDataRow=matching_row
        
        #Shows in combo box the current Item in used
        index= self.Model_C_ComBox_Int_Seed_Data.findText(str(CurrentSeedDataRow),QtCore.Qt.MatchFixedString)
        self.Model_C_ComBox_Int_Seed_Data.setCurrentIndex(index) #To set the item, consider (item from 1) (index from 0)    
        
        
        #Model is created (thread)
        query="SELECT * FROM Models WHERE Model_id=(SELECT max(Model_id) FROM Models)"
        self.Forcaster_DB_c.execute(query)
        Last_Model_row=self.Forcaster_DB_c.fetchall()
        if Last_Model_row==[]:
            LastModelRow=0
        else:    
            for j in Last_Model_row: 
                LastModelRow=j[0]
        self.model_creator.Set_Last_model_Crated(LastModelRow)
        
        self.model_creator.Set_SeedParam(CurrentSeedDataRow,LSTM1_Units,LSTM2_Units,LryDcoeff,Lyr_Dns,Lyr_Dn_Rgzr,OptAdam_Co,Colums,BackDays)
        
        self.model_creator.start()
        
    ############ General Fucntions  ############   
    def ModelTab_UpdateComboBoxModel_ID(self):
        #self.Model_C_ComBox_Int_Model.clear()
        self.GetModelTable()
        for i in self.ModelsData_SLCT_all: #ComboBox is updated
            Current_Row=i[0]
            self.Model_C_ComBox_Int_Model.addItem(str(Current_Row))
    
    def ModelsComboBoxChanged(self):
        Model_Selected=self.Model_C_ComBox_Int_Model.currentText()
        
        query="SELECT * FROM Models WHERE Model_id=?"
        
        self.Forcaster_DB_c.execute(query,(Model_Selected,))
        Select_Model=self.Forcaster_DB_c.fetchall()

        for i in Select_Model:   
            SeedDataModel=i[4]
        index= self.Model_C_ComBox_Int_Seed_Data.findText(str(SeedDataModel),QtCore.Qt.MatchFixedString)
        self.Model_C_ComBox_Int_Seed_Data.setCurrentIndex(index)  
       
    def SeedDataComboBoxChanged(self):
        Item_Selected=self.Model_C_ComBox_Int_Seed_Data.currentText()
        
        query="SELECT * FROM Seed_Data WHERE Seed_Data_id=?"
        
        self.Forcaster_DB_c.execute(query,(Item_Selected,))
        Select_SeedData=self.Forcaster_DB_c.fetchall()

        for i in Select_SeedData:  
            self.Model_C_txtLine_LSTM1.setText(str(i[2]))
            self.Model_C_txtLine_LSTM2.setText(str(i[3]))
            self.Model_C_txtLine_LryDCoeff.setText(str(i[4]))
            self.Model_C_txtLine_Lyr_Dns.setText(str(i[5]))
            self.Model_C_Lyr_Dn_Rgzr.setText(str(i[6]))
            self.Model_C_txtLine_OptAdam_Co.setText(str(i[7]))
            self.Model_C_txtLine_BackDays.setText(str(i[8]))
            self.Model_C_txtLine_Colums.setText(str(i[1]))
    
    def AddinElementComoBoxDataSeed(self,val1):
        #self.Model_C_ComBox_Int_Seed_Data.addItem(str(val1))
        self.UpdateLocalObjects()
    
    def AddinElementComoBoxModelData(self,val1):
        self.Model_C_ComBox_Int_Model.addItem(str(val1))
          
    def Check_Matching_DataSeed(self,val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8):
        Matching=False
        Matching_Row=0
        Matching_Val1=False
        Matching_Val2=False
        Matching_Val3=False
        Matching_Val4=False
        Matching_Val5=False
        Matching_Val6=False
        Matching_Val7=False
        Matching_Val8=False
        
        ##Seed_Data; Getting all data 
        query="SELECT * FROM Seed_Data"
         
        self.Forcaster_DB_c.execute(query)
        All_table_Data=self.Forcaster_DB_c.fetchall()
        
        for i in All_table_Data: 
            Matching_Row=i[0]
            
            if int(i[1])==int(val_1): Matching_Val1=True
            else: Matching_Val1=False

            if int(i[2])==int(val_2): Matching_Val2=True 
            else: Matching_Val2=False
            
            if int(i[3])==int(val_3): Matching_Val3=True 
            else: Matching_Val3=False
            
            if float(i[4])==float(val_4): Matching_Val4=True 
            else: Matching_Val4=False
            
            if int(i[5])==int(val_5): Matching_Val5=True 
            else: Matching_Val5=False
            
            if float(i[6])==float(val_6): Matching_Val6=True 
            else: Matching_Val6=False
            
            if str(i[7])==str(val_7): Matching_Val7=True 
            else: Matching_Val7=False
            
            if str(i[8])==str(val_8): Matching_Val8=True 
            else: Matching_Val8=False

            if Matching_Val1 and Matching_Val2 and Matching_Val3 and Matching_Val4 and Matching_Val5 and Matching_Val6 and Matching_Val7 and Matching_Val8==True:
                Matching=True
                break
            else:
                Matching_Row=0
        
        return Matching,Matching_Row
        
    def Create_new_DataSeed_DB(self,val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8):
        
        query=""" INSERT INTO Seed_Data (Columns_N,LSTM_1_N_Units, LSTM_2_N_Units,Lyr_Drop_Coeff,Lyr_Dns_N_Units,Lyr_Dns_Rgzr_Coeff,Optmzer_Adam_Coeff,BackDays)
         VALUES (?,?,?,?,?,?,?,?)"""

        self.Forcaster_DB_c.execute(query,(val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8)) 
        
        #Validate changes to our DB 
        self.Forcaster_DB_conn.commit()

    def Creare_new_model_in_DB(self,val_1,val_2,val_3,val_4,val_5,val_6,val_7):

        """date_Time TEXT,
        Path_Model TEXT,
        N_epochs_Done INTEGER,
        Seed_Data_id_FRGN INTEGER,
        DataSet_id_FRGN INTEGER"""
        
        query=""" INSERT INTO Models (date_Time,Path_Model, N_epochs_Done,Seed_Data_id_FRGN,DataSet_id_FRGN,Forcasting_Result_id_FRGN,Colm_T_Predict)
         VALUES (?,?,?,?,?,?,?)"""
        self.Forcaster_DB_c.execute(query,(val_1,val_2,val_3,val_4,val_5,val_6,val_7)) 
        
        #Validate changes to our DB 
        self.Forcaster_DB_conn.commit()

    ##### Emit thread signals
    
    def Event_ModelCreationStatus(self,val):
        date_Time,Path_Model,N_epochs_Done,Seed_Data_id_FRGN,DataSet_id_FRGN,Forcasting_Result_id_FRGN,Colm_T_Predict=self.model_creator.Get_NewModelData()
        NewModelStatus=self.model_creator.GetModelCreationStatus()
        print(NewModelStatus)

        if val:
            self.Creare_new_model_in_DB(date_Time,Path_Model,N_epochs_Done,Seed_Data_id_FRGN,DataSet_id_FRGN,Forcasting_Result_id_FRGN,Colm_T_Predict)
            print("Model Created :'D")
            modelJustCreated=self.model_creator.Get_Last_model_Create()+1
            self.AddinElementComoBoxModelData(modelJustCreated)
            index= self.Model_C_ComBox_Int_Model.findText(str(modelJustCreated),QtCore.Qt.MatchFixedString)
            self.Model_C_ComBox_Int_Model.setCurrentIndex(index)
            self.UpdateLocalObjects()
                
    def Event_UpdateProgress_ModelCreator(self,val):
        self.Model_C_LdBar.setProperty("value",val)
                
    def Event_UpdateProgress_string_ModelCreator(self,val): 
        self.Model_C_LBL_Progres.setText(val)
            
       
    ###########################################
    #              TAB Data Manager           #
    ###########################################
    
    ############### Bottons functions  ################   
    def Create_DataSet(self): 
        matching=False
        self.DaMa_btn_Create.setEnabled(False)
        CurrentSeedDataRow=0
        Item = self.DaMa_txtLine_Stock_Item.text()
        BackDays = self.DaMa_txtLine_BackDay.text()
        
        
        #Getting data from GUI
        if self.DaMa_CheckBox_Open.isChecked():Open_C=1
        else: Open_C=0
        
        if self.DaMa_CheckBox_High.isChecked():High_C=1
        else: High_C=0
        
        if self.DaMa_CheckBox_Low.isChecked():Low_C=1
        else: Low_C=0
        
        if self.DaMa_CheckBox_Close.isChecked():Close_C=1
        else: Close_C=0
        
        if self.DaMa_CheckBox_Volume.isChecked():Volume_C=1
        else: Volume_C=0
        
        if self.DaMa_CheckBox_Open_FFT.isChecked():Open_FFT_C=1
        else:Open_FFT_C=0
        
        if self.DaMa_CheckBox_High_FFT.isChecked(): High_FFT_C=1
        else:High_FFT_C=0
        
        if self.DaMa_CheckBox_Low_FFT.isChecked():Low_FFT_C=1
        else: Low_FFT_C=0
        
        if self.DaMa_CheckBox_Close_FFT.isChecked():Close_FFT_C=1
        else:Close_FFT_C=0
        
        if self.DaMa_CheckBox_Volume_FFT.isChecked(): Volum_FFT_C=1
        else:Volum_FFT_C=0
        
        if self.DaMa_CheckBox_DayNumber.isChecked():Day_Wk_N_C=1
        else:Day_Wk_N_C=0
        
        #if self.DaMa_CheckBox_Month_Number.isChecked():Month_N_C=1
        #else:Month_N_C=0
        
        if self.DaMa_CheckBox_Day_MonthNDay_C.isChecked(): Day_MonthNDay_C=1
        else: Day_MonthNDay_C=0
        
        if self.DaMa_CheckBox_Year.isChecked():Year_C=1
        else:Year_C=0
        
        FFT_Frec = self.DaMa_txtLine_FFT_Frec.text()
        
        #Check if seed data already exist
        matching,matching_row=self.Check_Matching_Seed_DataSet(Item,BackDays,Open_C ,High_C,Low_C,Close_C ,Volume_C,Open_FFT_C ,High_FFT_C ,Low_FFT_C,
                                                           Close_FFT_C ,Volum_FFT_C ,Day_Wk_N_C, Day_MonthNDay_C ,Year_C ,FFT_Frec)
        
        #new seed dataSet is created; if at least a feature has been changed
        if matching==False:
            self.Create_new_SeedDataSet_DB(Item,BackDays,Open_C ,High_C,Low_C,Close_C ,Volume_C,Open_FFT_C ,High_FFT_C ,Low_FFT_C,
                                        Close_FFT_C ,Volum_FFT_C ,Day_Wk_N_C ,Day_MonthNDay_C ,Year_C ,FFT_Frec)
            query="SELECT * FROM Seed_DataSet WHERE SeedDataSet_id=(SELECT max(SeedDataSet_id) FROM Seed_DataSet)"
            self.Forcaster_DB_c.execute(query)
            ContentList=self.Forcaster_DB_c.fetchall()
            for i in ContentList: 
                CurrentSeedDataRow=i[0]
            #Adding to Combo Box the data seed just created
            self.AddinElementComoBoxSeed_DataSet(CurrentSeedDataRow)
        else:
            CurrentSeedDataRow=matching_row
            
        #Shows in combo box the current Item in used
        index= self.DaMa_ComBox_Seed_DataSet.findText(str(CurrentSeedDataRow),QtCore.Qt.MatchFixedString)
        self.DaMa_ComBox_Seed_DataSet.setCurrentIndex(index) #To set the item, consider (item from 1) (index from 0)
        
        
        #DataSet is created (thread)
        query="SELECT * FROM DataSet WHERE DataSet_id=(SELECT max(DataSet_id) FROM DataSet)"
        self.Forcaster_DB_c.execute(query)
        Last_DataSet_row=self.Forcaster_DB_c.fetchall()
        if Last_DataSet_row==[]:
            LastDataSetRow=0
        else:    
            for j in Last_DataSet_row: 
                LastDataSetRow=j[0]
                
        #SeedData 
        query="SELECT * FROM Seed_DataSet WHERE SeedDataSet_id=?"
        self.Forcaster_DB_c.execute(query,(CurrentSeedDataRow,))
        Last_SetDataSet_row=self.Forcaster_DB_c.fetchall()[0]
        
        
        #Set the last dataset row
        self.DataSet_creator.Set_Last_DataSet_Crated(LastDataSetRow)
        
        self.DataSet_creator.Set_SeedParam(Last_SetDataSet_row)
        
        self.DataSet_creator.Set_TypeProcessToDo("1") #Process
        
        self.DataSet_creator.start()      
    
    def Update_DataSet(self):
        pass

    ############ General Fucntions  ############
    def DataManagerTab_UpdateComboxDataSet_ID(self):
        #self.DaMa_ComBox_DataSet_Id.clear() #When starting app, combobox is updated
        self.GetDataSetTable()
        for i in self.DataSet_all: #ComboBox is updated
            Current_Row=i[0]
            index= self.DaMa_ComBox_DataSet_Id.findText(str(Current_Row),QtCore.Qt.MatchFixedString)
            if index==-1:
                self.DaMa_ComBox_DataSet_Id.addItem(str(Current_Row))
            
        #self.SeedDataSetComboBoxChanged() 
        
    def DataManagerTab_UpdateComboxSeedDataSet_ID(self):
        #self.DaMa_ComBox_Seed_DataSet.clear() #When starting app, combobox is updated
        self.GetSeed_DataSet()
        for i in self.SeedDataSet_all: #ComboBox is updated
            Current_Row=i[0]
            index= self.DaMa_ComBox_Seed_DataSet.findText(str(Current_Row),QtCore.Qt.MatchFixedString)
            if index==-1:
                self.DaMa_ComBox_Seed_DataSet.addItem(str(Current_Row))
            
        #self.SeedDataSetComboBoxChanged() 
        
    def DataSetComboBoxChanged(self):
        DatasSet_Selected=self.DaMa_ComBox_DataSet_Id.currentText()
        print(DatasSet_Selected)
        query="SELECT * FROM DataSet WHERE DataSet_id=?"
        
        self.Forcaster_DB_c.execute(query,(DatasSet_Selected,))
        Select_DataSet=self.Forcaster_DB_c.fetchall()
        
        print(Select_DataSet)

        for i in Select_DataSet:
            Date_Time_DataSet=i[1]
            Path_DataSet=i[2]
            SeedDataSet=i[3]
        
        print(Date_Time_DataSet)
        print(Path_DataSet)
        print(SeedDataSet)
        
    
        self.DaMa_txtLine_DateTime.setText(str(Date_Time_DataSet))
        self.DaMa_txtLine_PathCSV_File.setText(str(Path_DataSet))
        index= self.DaMa_ComBox_Seed_DataSet.findText(str(SeedDataSet),QtCore.Qt.MatchFixedString)
        self.DaMa_ComBox_Seed_DataSet.setCurrentIndex(index)
        
    
    def SeedDataSetComboBoxChanged(self):
        Item_Selected=self.DaMa_ComBox_Seed_DataSet.currentText()
        
        query="SELECT * FROM Seed_DataSet WHERE SeedDataSet_id=?"
        
        self.Forcaster_DB_c.execute(query,(Item_Selected,))
        Select_SeedDataSet=self.Forcaster_DB_c.fetchall()
        
        #Setting data to GUI
        for i in Select_SeedDataSet:  
            self.DaMa_txtLine_Stock_Item.setText(str(i[1]))
            self.DaMa_txtLine_BackDay.setText(str(i[2]))
            
            # data from GUI
            if i[3]==1:self.DaMa_CheckBox_Open.setChecked(True)
            else:self.DaMa_CheckBox_Open.setChecked(False)
            
            if i[4]==1:self.DaMa_CheckBox_High.setChecked(True)
            else: self.DaMa_CheckBox_High.setChecked(False)
            
            if i[5]==1:self.DaMa_CheckBox_Low.setChecked(True)
            else: self.DaMa_CheckBox_Low.setChecked(False)
            
            if i[6]==1:self.DaMa_CheckBox_Close.setChecked(True)
            else: self.DaMa_CheckBox_Close.setChecked(False)
            
            if i[7]==1:self.DaMa_CheckBox_Volume.setChecked(True)
            else: self.DaMa_CheckBox_Volume.setChecked(False)
            
            if i[8]==1:self.DaMa_CheckBox_Open_FFT.setChecked(True)
            else:self.DaMa_CheckBox_Open_FFT.setChecked(False)
            
            if i[9]==1: self.DaMa_CheckBox_High_FFT.setChecked(True)
            else:self.DaMa_CheckBox_High_FFT.setChecked(False)
            
            if i[10]==1:self.DaMa_CheckBox_Low_FFT.setChecked(True)
            else: self.DaMa_CheckBox_Low_FFT.setChecked(False)
            
            if i[11]==1:self.DaMa_CheckBox_Close_FFT.setChecked(True)
            else:self.DaMa_CheckBox_Close_FFT.setChecked(False)
            
            if i[12]==1: self.DaMa_CheckBox_Volume_FFT.setChecked(True)
            else:self.DaMa_CheckBox_Volume_FFT.setChecked(False)
            
            if i[13]==1:self.DaMa_CheckBox_DayNumber.setChecked(True)
            else:self.DaMa_CheckBox_DayNumber.setChecked(False)
            
            #if i[14]==1:self.DaMa_CheckBox_Month_Number.setChecked(True)
            #else:self.DaMa_CheckBox_Month_Number.setChecked(False)
            
            if i[14]==1: self.DaMa_CheckBox_Day_MonthNDay_C.setChecked(True)
            else: self.DaMa_CheckBox_Day_MonthNDay_C.setChecked(False)
            
            if i[15]==1:self.DaMa_CheckBox_Year.setChecked(True)
            else:self.DaMa_CheckBox_Year.setChecked(False)
            
            self.DaMa_txtLine_FFT_Frec.setText(str(i[16]))
              
    def AddinElementComoBoxSeed_DataSet(self,val1):
        self.DaMa_ComBox_Seed_DataSet.addItem(str(val1))
        
    def AddinElementComoBoxData_Set(self,val1):
        self.DaMa_ComBox_DataSet_Id.addItem(str(val1))
        
    def Check_Matching_Seed_DataSet(self,val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8,
                                    val_9,val_10,val_11,val_12,val_13,val_14,val_15,val_16):
        Matching=False
        Matching_Row=0
        Matching_Val1=False
        Matching_Val2=False
        Matching_Val3=False
        Matching_Val4=False
        Matching_Val5=False
        Matching_Val6=False
        Matching_Val7=False
        Matching_Val8=False
        Matching_Val9=False
        Matching_Val10=False
        Matching_Val11=False
        Matching_Val12=False
        Matching_Val13=False
        Matching_Val14=False
        Matching_Val15=False
        Matching_Val16=False
        
        ##Seed_Data; Getting all data 
        query="SELECT * FROM Seed_DataSet"
         
        self.Forcaster_DB_c.execute(query)
        All_table_Data=self.Forcaster_DB_c.fetchall()
        
        for i in All_table_Data: 
            Matching_Row=i[0]
            
            if str(i[1])==str(val_1): Matching_Val1=True
            else: Matching_Val1=False

            if int(i[2])==int(val_2): Matching_Val2=True 
            else: Matching_Val2=False
            
            if int(i[3])==int(val_3): Matching_Val3=True 
            else: Matching_Val3=False
            
            if int(i[4])==int(val_4): Matching_Val4=True 
            else: Matching_Val4=False
            
            if int(i[5])==int(val_5): Matching_Val5=True 
            else: Matching_Val5=False
            
            if int(i[6])==int(val_6): Matching_Val6=True 
            else: Matching_Val6=False
            
            if int(i[7])==int(val_7): Matching_Val7=True 
            else: Matching_Val7=False
            
            if int(i[8])==int(val_8): Matching_Val8=True 
            else: Matching_Val8=False
            
            if int(i[9])==int(val_9): Matching_Val9=True 
            else: Matching_Val9=False
            
            if int(i[10])==int(val_10): Matching_Val10=True 
            else: Matching_Val10=False
            
            if int(i[11])==int(val_11): Matching_Val11=True 
            else: Matching_Val11=False
            
            if int(i[12])==int(val_12): Matching_Val12=True 
            else: Matching_Val12=False
            
            if int(i[13])==int(val_13): Matching_Val13=True 
            else: Matching_Val13=False
            
            if int(i[14])==int(val_14): Matching_Val14=True 
            else: Matching_Val14=False
            
            if int(i[15])==int(val_15): Matching_Val15=True 
            else: Matching_Val15=False
            
            if str(i[16])==str(val_16): Matching_Val16=True 
            else: Matching_Val16=False
            

            if (Matching_Val1 and Matching_Val2 and Matching_Val3 and Matching_Val4 and Matching_Val5 and Matching_Val6 and Matching_Val7 and Matching_Val8
                and Matching_Val9 and Matching_Val10 and Matching_Val11 and Matching_Val12 and Matching_Val13 and Matching_Val14 and Matching_Val15 and 
                Matching_Val16):
                Matching=True
                break
            else:
                Matching_Row=0
        
        return Matching,Matching_Row
        
    def Create_new_SeedDataSet_DB(self,val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8,
                                    val_9,val_10,val_11,val_12,val_13,val_14,val_15,val_16):
        
        query=""" INSERT INTO Seed_DataSet (Item,BackDays,Open_C ,High_C,Low_C,Close_C ,Volume_C,Open_FFT_C ,High_FFT_C ,Low_FFT_C,
                                        Close_FFT_C ,Volum_FFT_C ,Day_Wk_N_C, Day_MonthNDay_C ,Year_C ,FFT_Frec)
         VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""

        self.Forcaster_DB_c.execute(query,(val_1,val_2,val_3,val_4,val_5,val_6,val_7,val_8,val_9,
                                    val_10,val_11,val_12,val_13,val_14,val_15,val_16)) 
        
        #Validate changes to our DB 
        self.Forcaster_DB_conn.commit()
        
    def Creare_new_DataSet_in_DB(self,val_1,val_2,val_3):
        """Date_Time TEXT,
            Path_DataSet TEXT,
            Seed_DataSet_id_FRGN INTEGER"""
        
        query=""" INSERT INTO DataSet (Date_Time,Path_DataSet,Seed_DataSet_id_FRGN)
         VALUES (?,?,?)"""

        self.Forcaster_DB_c.execute(query,(val_1,val_2,val_3)) 
        
        #Validate changes to our DB 
        self.Forcaster_DB_conn.commit()
    
    ##### Emit thread signals
    
    def Event_DataSetCreationStatus(self,val):
        Date_Time,Path_DataSet,Seed_DataSet_id_FRGN=self.DataSet_creator.Get_NewDataSet_Data()

        if val:
            self.Creare_new_DataSet_in_DB(Date_Time,Path_DataSet,Seed_DataSet_id_FRGN)
            print("DataSet created Created :'D")
            self.DaMa_btn_Create.setEnabled(True)
            DataSetJustCreated=self.DataSet_creator.Get_DataSet_id_Just_Created()
            self.AddinElementComoBoxData_Set(DataSetJustCreated)
            index= self.DaMa_ComBox_DataSet_Id.findText(str(DataSetJustCreated),QtCore.Qt.MatchFixedString)
            self.DaMa_ComBox_DataSet_Id.setCurrentIndex(index)
            self.UpdateLocalObjects()
            
            
    def Event_UpdateProgress_DataSetCreator(self,val):
         self.DaMa_LoadBar_Progres.setProperty("value",val)
    
    def Event_UpdateProgress_string_DataSetCreator(self,val):
        self.DaMa_Lbl_Progres.setText(val)
        
        
    ###########################################
    #           TAB Model Trainning           #
    ###########################################
    
    ############### Bottons functions  ################ 
    def Start_Trainning(self):
        
        #Getting data form GUI
        Id_modelSelect=self.MoTr_ComBox_ChooseModel.currentText()
        Colum_To_Predict=self.MoTr_ComBox_Column_T_Predict.currentText()
        DataSet_Id=self.MoTr_ComBox_DataSet.currentText()
        N_Epohc=self.MoTr_txtLine_ephocs.text()
        N_PercentData=self.MoTr_txtLine_PercentDataSet.text()        
        
        ## Getting the DB row model 
        query="SELECT * FROM Models WHERE Model_id=?"
        self.Forcaster_DB_c.execute(query,(Id_modelSelect,))
        Model_Selected_Row=self.Forcaster_DB_c.fetchall()[0]
        
        ModelPath=Model_Selected_Row[2]
        DataSetMarried=int(Model_Selected_Row[5])
        ColmTPredictMarried=int(Model_Selected_Row[7])
        
        Columns_Index=self.Mapping_DataSetColums(DataSet_Id,Colum_To_Predict)
        
        #Missing to do a mapping DataSetMarried and COlumns to predrict
        
        #in case not dataset and column married to model 
        if DataSetMarried==0 and ColmTPredictMarried==0:
            query="UPDATE Models SET DataSet_id_FRGN = ?,Colm_T_Predict=? WHERE Model_id=?"
            self.Forcaster_DB_c.execute(query,(DataSet_Id,Columns_Index,Id_modelSelect))
            self.Forcaster_DB_conn.commit()
        else:
            print("This model is already married to a Dataset and a Column ")
            
        ## Getting the DB row DataSet 
        query="SELECT * FROM DataSet WHERE DataSet_id=?"
        self.Forcaster_DB_c.execute(query,(DataSet_Id,))
        DataSet_Selected_Row=self.Forcaster_DB_c.fetchall()[0]
        
        dataSetPath=DataSet_Selected_Row[2]
        dataSetSeed=str(DataSet_Selected_Row[3])
        
        ## Getting the DB row seed DataSet 
        query="SELECT * FROM Seed_DataSet WHERE SeedDataSet_id=?"
        self.Forcaster_DB_c.execute(query,(dataSetSeed,))
        SeedDataSet_Selected_Row=self.Forcaster_DB_c.fetchall()[0]
        
        DataSetBackDays=SeedDataSet_Selected_Row[2]
        
        self.trainner.SetColumToForcast(Columns_Index) #from function mappe colum considering the data set
        self.trainner.SetnumEpochs(N_Epohc) #from GUI direct
        self.trainner.SetModel_Path(ModelPath) #from DB model
        self.trainner.SetData_CSV(dataSetPath) #From DB DataSet
        self.trainner.SetpercentageData(N_PercentData) # directly from gui
        self.trainner.SetNp_pasdays(DataSetBackDays) #from data set choosed - from ** Seed dataset **
        self.trainner.start()
    
    def Cancel_Trainning(self):   
        #This button may also breake the data set and columns marriage
        pass 
    
    ############ General Fucntions  ############
    
    def TrainningTab_UpdateComboxModel_ID(self):
        #self.MoTr_ComBox_ChooseModel.clear()
        self.GetModelTable()
        for i in self.ModelsData_SLCT_all: #ComboBox is updated
            Current_Row=i[0]
            index= self.MoTr_ComBox_ChooseModel.findText(str(Current_Row),QtCore.Qt.MatchFixedString)
            if index==-1:
                self.MoTr_ComBox_ChooseModel.addItem(str(Current_Row))
            
            
    def TrainningTab_UpdateComboxDataSet_ID(self):
        #self.MoTr_ComBox_DataSet.clear()
        self.GetDataSetTable()
        for i in self.DataSet_all: #ComboBox is updated
            Current_Row=i[0]
            index= self.DaMa_ComBox_Seed_DataSet.findText(str(Current_Row),QtCore.Qt.MatchFixedString)
            if index==-1:
                self.MoTr_ComBox_DataSet.addItem(str(Current_Row))
                
    def Mapping_DataSetColums(self,DataSetId,ColumnSelected):
        ## Getting the DB row DataSet 
        query="SELECT * FROM DataSet WHERE DataSet_id=?"
        self.Forcaster_DB_c.execute(query,(DataSetId,))
        Model_Selected_Row=self.Forcaster_DB_c.fetchall()[0]
        
        DataSetPath=Model_Selected_Row[2]

        all_df=pd.read_csv(DataSetPath,index_col=0)
        ColumnsList=all_df.columns
        
        index=0
        for i in ColumnsList:
            if ColumnSelected == i:
                break
            index+=1
        
        return(index)
        
        
        ## Need to get the data set path using the DB with DataSet_Id then
        ## Need to get the data in a pandas data frame Then
        ## Map the colum possition using Colum_To_Predict 
            
    ##### Emit general signals
    def Model_To_Train_ComboBoxChanged(self):
        Id_modelSelect=self.MoTr_ComBox_ChooseModel.currentText()
        Colum_To_Predict=self.MoTr_ComBox_Column_T_Predict.currentText()
        DataSet_Id=self.MoTr_ComBox_DataSet.currentText()
        print(Id_modelSelect)
        print(type(Id_modelSelect))
        ## Getting the DB row model 
        query="SELECT * FROM Models WHERE Model_id=?"
        self.Forcaster_DB_c.execute(query,(Id_modelSelect,))
        Model_Selected_Row=self.Forcaster_DB_c.fetchall()[0]
        
        DataSetMarried=int(Model_Selected_Row[5])
        ColmTPredictMarried=int(Model_Selected_Row[7])
        
        if DataSetMarried>0:
            ### if has already a DataSet married to, let's bring it on
            index= self.MoTr_ComBox_DataSet.findText(str(DataSetMarried),QtCore.Qt.MatchFixedString)
            self.MoTr_ComBox_DataSet.setCurrentIndex(index)
        
            
        if ColmTPredictMarried>0:
            ### if has already a Colum to predict married to, let's bring it on
            index= self.MoTr_ComBox_Column_T_Predict.findText(str(ColmTPredictMarried),QtCore.Qt.MatchFixedString)
            self.MoTr_ComBox_Column_T_Predict.setCurrentIndex(index)
        
    
    ##### Emit thread signals
    
    def Event_TrainningStatus(self):
        pass
    
    def Event_UpdateProgress_TrainningProcess(self):
        pass
    
    def Event_UpdateProgress_string_Trainning_Process(self):
        pass
                 
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_LSTM_FORCASTER = QtWidgets.QMainWindow()
    ui = Ui_GUI_LSTM_FORCASTER()
    ui.setupUi(GUI_LSTM_FORCASTER)
    GUI_LSTM_FORCASTER.show()
    sys.exit(app.exec_())