# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QT_Files/GUI_FFT_LSTM_Stock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GUI_LSTM_FORCASTER(object):
    def __init__(self):
        self.Model_Path="FFT_added_LSTM_All_In_Close_Out_all_relu_added_HG_X/ModelGen/Model/Models_fewColums/Model_LSTM_CloseDayMonthYearFFT_only900FFT"
        self.Data_CSV="FFT_added_LSTM_All_In_Close_Out_all_relu_added_HG_X/DatasetGen/CRUDE_OIL/CRUDE_OIL_Dataand_FFT_900.csv"
        self.percentageData=95
        self.forcastPath="FFT_added_LSTM_All_In_Close_Out_all_relu_added_HG_X/ModelGen/Forcasts/Focast_CloseDayMonthYearFFT90019_02_2023.csv"
        ##################################################################
        #                       Init ComboBoxData                        #
        ################################################################## 
        """self.BaCon_Combox_ChooseModel
        self.ForC_ComBox_DateFrom 
        self.MoTr_ComBox_ChooseModel
        self.DaMa_ComBox_ChooseDataset"""
        ##################################################################
        #                       Init txtLine                             #
        ##################################################################
        """self.BaCon_txtLine_DatasetBelongs 
        self.ForC_txtLine_TailBackDays
        self.MoTr_txtLine_DataSet
        self.MoTr_txtLine_PercentDataSet
        self.DaMa_txtLine_Modelbelongs"""
        
        ##################################################################
        #                          Init lbl                              #
        ##################################################################
        """self.ForC_lbl_TodayPrice
        self.ForC_lbl_TomorrowPrice
        self.ForC_lbl_LoadStatus
        self.DaMA_lbl_loadStatus"""
        
    
    def setupUi(self, GUI_LSTM_FORCASTER):
        GUI_LSTM_FORCASTER.setObjectName("GUI_LSTM_FORCASTER")
        GUI_LSTM_FORCASTER.resize(683, 446)
        self.centralwidget = QtWidgets.QWidget(GUI_LSTM_FORCASTER)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 0, 681, 421))
        self.Tabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setMovable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.BasicConf_Tab = QtWidgets.QWidget()
        self.BasicConf_Tab.setObjectName("BasicConf_Tab")
        self.BaCon_lbl_ChooseModel = QtWidgets.QLabel(self.BasicConf_Tab)
        self.BaCon_lbl_ChooseModel.setGeometry(QtCore.QRect(28, 50, 161, 20))
        self.BaCon_lbl_ChooseModel.setObjectName("BaCon_lbl_ChooseModel")
        self.BaCon_lbl_DatasetBelongs = QtWidgets.QLabel(self.BasicConf_Tab)
        self.BaCon_lbl_DatasetBelongs.setGeometry(QtCore.QRect(30, 130, 231, 16))
        self.BaCon_lbl_DatasetBelongs.setObjectName("BaCon_lbl_DatasetBelongs")
        self.BaCon_btn_SetConfig = QtWidgets.QPushButton(self.BasicConf_Tab)
        self.BaCon_btn_SetConfig.setGeometry(QtCore.QRect(520, 190, 113, 32))
        self.BaCon_btn_SetConfig.setObjectName("BaCon_btn_SetConfig")
        self.BaCon_Combox_ChooseModel = QtWidgets.QComboBox(self.BasicConf_Tab)
        self.BaCon_Combox_ChooseModel.setGeometry(QtCore.QRect(26, 70, 361, 26))
        self.BaCon_Combox_ChooseModel.setObjectName("BaCon_Combox_ChooseModel")
        self.BaCon_txtLine_DatasetBelongs = QtWidgets.QLineEdit(self.BasicConf_Tab)
        self.BaCon_txtLine_DatasetBelongs.setGeometry(QtCore.QRect(30, 150, 351, 21))
        self.BaCon_txtLine_DatasetBelongs.setObjectName("BaCon_txtLine_DatasetBelongs")
        self.Tabs.addTab(self.BasicConf_Tab, "")
        self.Forcasting_Tab = QtWidgets.QWidget()
        self.Forcasting_Tab.setObjectName("Forcasting_Tab")
        self.ForC_Loadbar_Forcast = QtWidgets.QProgressBar(self.Forcasting_Tab)
        self.ForC_Loadbar_Forcast.setGeometry(QtCore.QRect(140, 240, 391, 61))
        self.ForC_Loadbar_Forcast.setProperty("value", 24)
        self.ForC_Loadbar_Forcast.setObjectName("ForC_Loadbar_Forcast")
        self.ForC_ComBox_DateFrom = QtWidgets.QComboBox(self.Forcasting_Tab)
        self.ForC_ComBox_DateFrom.setGeometry(QtCore.QRect(50, 50, 221, 26))
        self.ForC_ComBox_DateFrom.setObjectName("ForC_ComBox_DateFrom")
        self.ForC_lbl_DateFrom = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_DateFrom.setGeometry(QtCore.QRect(50, 30, 60, 16))
        self.ForC_lbl_DateFrom.setObjectName("ForC_lbl_DateFrom")
        self.ForC_btn_StartForcasting = QtWidgets.QPushButton(self.Forcasting_Tab)
        self.ForC_btn_StartForcasting.setGeometry(QtCore.QRect(350, 110, 221, 101))
        self.ForC_btn_StartForcasting.setObjectName("ForC_btn_StartForcasting")
        self.ForC_radioButton_GetGraph = QtWidgets.QRadioButton(self.Forcasting_Tab)
        self.ForC_radioButton_GetGraph.setGeometry(QtCore.QRect(370, 50, 111, 20))
        self.ForC_radioButton_GetGraph.setObjectName("ForC_radioButton_GetGraph")
        self.ForC_lbl_LoadStatus = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_LoadStatus.setGeometry(QtCore.QRect(140, 230, 171, 16))
        self.ForC_lbl_LoadStatus.setObjectName("ForC_lbl_LoadStatus")
        self.ForC_Gbox_ForcastResul = QtWidgets.QGroupBox(self.Forcasting_Tab)
        self.ForC_Gbox_ForcastResul.setGeometry(QtCore.QRect(50, 110, 251, 91))
        self.ForC_Gbox_ForcastResul.setObjectName("ForC_Gbox_ForcastResul")
        self.label_13 = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_5.setObjectName("label_5")
        self.ForC_lbl_TodayPrice = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.ForC_lbl_TodayPrice.setGeometry(QtCore.QRect(130, 31, 121, 16))
        self.ForC_lbl_TodayPrice.setObjectName("ForC_lbl_TodayPrice")
        self.ForC_lbl_TomorrowPrice = QtWidgets.QLabel(self.ForC_Gbox_ForcastResul)
        self.ForC_lbl_TomorrowPrice.setGeometry(QtCore.QRect(130, 61, 101, 16))
        self.ForC_lbl_TomorrowPrice.setObjectName("ForC_lbl_TomorrowPrice")
        self.ForC_txtLine_TailBackDays = QtWidgets.QLineEdit(self.Forcasting_Tab)
        self.ForC_txtLine_TailBackDays.setGeometry(QtCore.QRect(490, 50, 113, 21))
        self.ForC_txtLine_TailBackDays.setObjectName("ForC_txtLine_TailBackDays")
        self.ForC_lbl_TailBackDays = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_TailBackDays.setGeometry(QtCore.QRect(370, 30, 121, 16))
        self.ForC_lbl_TailBackDays.setObjectName("ForC_lbl_TailBackDays")
        self.ForC_lbl_or = QtWidgets.QLabel(self.Forcasting_Tab)
        self.ForC_lbl_or.setGeometry(QtCore.QRect(320, 53, 21, 16))
        self.ForC_lbl_or.setObjectName("ForC_lbl_or")
        self.Tabs.addTab(self.Forcasting_Tab, "")
        self.Model_Trainner_Tab = QtWidgets.QWidget()
        self.Model_Trainner_Tab.setObjectName("Model_Trainner_Tab")
        self.MoTr_lbl_chooseModel = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_chooseModel.setGeometry(QtCore.QRect(110, 30, 111, 16))
        self.MoTr_lbl_chooseModel.setObjectName("MoTr_lbl_chooseModel")
        self.MoTr_lbl_DataSet = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_DataSet.setGeometry(QtCore.QRect(110, 80, 60, 16))
        self.MoTr_lbl_DataSet.setObjectName("MoTr_lbl_DataSet")
        self.MoTr_txtLine_DataSet = QtWidgets.QLineEdit(self.Model_Trainner_Tab)
        self.MoTr_txtLine_DataSet.setGeometry(QtCore.QRect(110, 100, 311, 21))
        self.MoTr_txtLine_DataSet.setObjectName("MoTr_txtLine_DataSet")
        self.MoTr_btn_Totrain = QtWidgets.QPushButton(self.Model_Trainner_Tab)
        self.MoTr_btn_Totrain.setGeometry(QtCore.QRect(470, 60, 141, 51))
        self.MoTr_btn_Totrain.setObjectName("MoTr_btn_Totrain")
        self.MoTr_Plaintxt_CMDTraining = QtWidgets.QPlainTextEdit(self.Model_Trainner_Tab)
        self.MoTr_Plaintxt_CMDTraining.setGeometry(QtCore.QRect(10, 210, 661, 171))
        self.MoTr_Plaintxt_CMDTraining.setObjectName("MoTr_Plaintxt_CMDTraining")
        self.MoTr_lbl_CMD_training = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_CMD_training.setGeometry(QtCore.QRect(10, 190, 161, 16))
        self.MoTr_lbl_CMD_training.setObjectName("MoTr_lbl_CMD_training")
        self.MoTr_txtLine_PercentDataSet = QtWidgets.QLineEdit(self.Model_Trainner_Tab)
        self.MoTr_txtLine_PercentDataSet.setGeometry(QtCore.QRect(110, 150, 61, 21))
        self.MoTr_txtLine_PercentDataSet.setObjectName("MoTr_txtLine_PercentDataSet")
        self.MoTr_lbl_PercentDataset = QtWidgets.QLabel(self.Model_Trainner_Tab)
        self.MoTr_lbl_PercentDataset.setGeometry(QtCore.QRect(110, 130, 111, 16))
        self.MoTr_lbl_PercentDataset.setObjectName("MoTr_lbl_PercentDataset")
        self.MoTr_ComBox_ChooseModel = QtWidgets.QComboBox(self.Model_Trainner_Tab)
        self.MoTr_ComBox_ChooseModel.setGeometry(QtCore.QRect(106, 50, 311, 26))
        self.MoTr_ComBox_ChooseModel.setObjectName("MoTr_ComBox_ChooseModel")
        self.Tabs.addTab(self.Model_Trainner_Tab, "")
        
        ######## Data Manager ##############
        self.Data_Manager_tab = QtWidgets.QWidget()
        self.Data_Manager_tab.setObjectName("Data_Manager_tab")
        self.DaMa_lbl_Modelbelongs = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_Modelbelongs.setGeometry(QtCore.QRect(80, 130, 201, 16))
        self.DaMa_lbl_Modelbelongs.setObjectName("DaMa_lbl_Modelbelongs")
        self.DaMa_txtLine_Modelbelongs = QtWidgets.QLineEdit(self.Data_Manager_tab)
        self.DaMa_txtLine_Modelbelongs.setGeometry(QtCore.QRect(90, 150, 361, 21))
        self.DaMa_txtLine_Modelbelongs.setObjectName("DaMa_txtLine_Modelbelongs")
        self.DaMa_btn_Update = QtWidgets.QPushButton(self.Data_Manager_tab)
        self.DaMa_btn_Update.setGeometry(QtCore.QRect(490, 80, 113, 101))
        self.DaMa_btn_Update.setObjectName("DaMa_btn_Update")
        self.DaMa_LoadBar_UpdateData = QtWidgets.QProgressBar(self.Data_Manager_tab)
        self.DaMa_LoadBar_UpdateData.setGeometry(QtCore.QRect(150, 260, 411, 41))
        self.DaMa_LoadBar_UpdateData.setProperty("value", 24)
        self.DaMa_LoadBar_UpdateData.setObjectName("DaMa_LoadBar_UpdateData")
        self.DaMA_lbl_loadStatus = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMA_lbl_loadStatus.setGeometry(QtCore.QRect(150, 250, 60, 16))
        self.DaMA_lbl_loadStatus.setObjectName("DaMA_lbl_loadStatus")
        self.DaMa_ComBox_ChooseDataset = QtWidgets.QComboBox(self.Data_Manager_tab)
        self.DaMa_ComBox_ChooseDataset.setGeometry(QtCore.QRect(80, 80, 371, 26))
        self.DaMa_ComBox_ChooseDataset.setObjectName("DaMa_ComBox_ChooseDataset")
        self.DaMa_lbl_ChooseDataset = QtWidgets.QLabel(self.Data_Manager_tab)
        self.DaMa_lbl_ChooseDataset.setGeometry(QtCore.QRect(80, 60, 201, 16))
        self.DaMa_lbl_ChooseDataset.setObjectName("DaMa_lbl_ChooseDataset")
        self.Tabs.addTab(self.Data_Manager_tab, "")
        GUI_LSTM_FORCASTER.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(GUI_LSTM_FORCASTER)
        self.statusbar.setObjectName("statusbar")
        GUI_LSTM_FORCASTER.setStatusBar(self.statusbar)

        self.retranslateUi(GUI_LSTM_FORCASTER)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GUI_LSTM_FORCASTER)
        
        ##################################################################
        #                    Thread signals arrival                      #
        ##################################################################
        
        ##################################################################
        #                          buttons call                          #
        ##################################################################
        

    def retranslateUi(self, GUI_LSTM_FORCASTER):
        _translate = QtCore.QCoreApplication.translate
        GUI_LSTM_FORCASTER.setWindowTitle(_translate("GUI_LSTM_FORCASTER", "MainWindow"))
        self.BaCon_lbl_ChooseModel.setText(_translate("GUI_LSTM_FORCASTER", "To choose the model"))
        self.BaCon_lbl_DatasetBelongs.setText(_translate("GUI_LSTM_FORCASTER", "Dataset that belongs to model"))
        self.BaCon_btn_SetConfig.setText(_translate("GUI_LSTM_FORCASTER", "Set Config"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.BasicConf_Tab), _translate("GUI_LSTM_FORCASTER", "Basic Config"))
        self.ForC_lbl_DateFrom.setText(_translate("GUI_LSTM_FORCASTER", "Date from"))
        self.ForC_btn_StartForcasting.setText(_translate("GUI_LSTM_FORCASTER", "START FORCASTING"))
        self.ForC_radioButton_GetGraph.setText(_translate("GUI_LSTM_FORCASTER", "Get the graph?"))
        self.ForC_lbl_LoadStatus.setText(_translate("GUI_LSTM_FORCASTER", "Ready to forcast"))
        self.ForC_Gbox_ForcastResul.setTitle(_translate("GUI_LSTM_FORCASTER", "Forcast Result Close"))
        self.label_13.setText(_translate("GUI_LSTM_FORCASTER", "Today Close price:"))
        self.label_5.setText(_translate("GUI_LSTM_FORCASTER", "Tomorrow forcast:"))
        self.ForC_lbl_TodayPrice.setText(_translate("GUI_LSTM_FORCASTER", "2334"))
        self.ForC_lbl_TomorrowPrice.setText(_translate("GUI_LSTM_FORCASTER", "234"))
        self.ForC_txtLine_TailBackDays.setText(_translate("GUI_LSTM_FORCASTER", "200"))
        self.ForC_lbl_TailBackDays.setText(_translate("GUI_LSTM_FORCASTER", "Tail backdays"))
        self.ForC_lbl_or.setText(_translate("GUI_LSTM_FORCASTER", "Or"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Forcasting_Tab), _translate("GUI_LSTM_FORCASTER", "Forcasting"))
        self.MoTr_lbl_chooseModel.setText(_translate("GUI_LSTM_FORCASTER", "To choose Model"))
        self.MoTr_lbl_DataSet.setText(_translate("GUI_LSTM_FORCASTER", "DataSet"))
        self.MoTr_btn_Totrain.setText(_translate("GUI_LSTM_FORCASTER", "To train"))
        self.MoTr_lbl_CMD_training.setText(_translate("GUI_LSTM_FORCASTER", "CMD training process"))
        self.MoTr_lbl_PercentDataset.setText(_translate("GUI_LSTM_FORCASTER", "% Data to test"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Model_Trainner_Tab), _translate("GUI_LSTM_FORCASTER", "Model Trainner"))
                    ######################
        ##############  Tada manager Tab ###############
        self.DaMa_lbl_Modelbelongs.setText(_translate("GUI_LSTM_FORCASTER", "Model DataSet belongs to"))
        self.DaMa_btn_Update.setText(_translate("GUI_LSTM_FORCASTER", "Update"))
        self.DaMA_lbl_loadStatus.setText(_translate("GUI_LSTM_FORCASTER", "Ready"))
        self.DaMa_lbl_ChooseDataset.setText(_translate("GUI_LSTM_FORCASTER", "To choose DataSet"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Data_Manager_tab), _translate("GUI_LSTM_FORCASTER", "Data manager"))
                    #################
        ############# Model Creatio ##############
        self.ModCrtion_lbl_Modelbelongs.setText(_translate("GUI_LSTM_FORCASTER", "Model DataSet belongs to"))
        self.ModCrtion_btn_Update.setText(_translate("GUI_LSTM_FORCASTER", "Update"))
        self.ModCrtion_lbl_loadStatus.setText(_translate("GUI_LSTM_FORCASTER", "Ready"))
        self.ModCrtion_lbl_ChooseDataset.setText(_translate("GUI_LSTM_FORCASTER", "To choose DataSet"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Model_Creation_tab), _translate("GUI_LSTM_FORCASTER", "Model Creation"))
    
    ##################################################################
    #                       Funct Forcaster                          #
    ##################################################################
    def ToForcast(self):
        pass
    
    ##################################################################
    #                    DataManager Forcaster                       #
    ##################################################################
    def ToUpDate(self):
        pass
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GUI_LSTM_FORCASTER = QtWidgets.QMainWindow()
    ui = Ui_GUI_LSTM_FORCASTER()
    ui.setupUi(GUI_LSTM_FORCASTER)
    GUI_LSTM_FORCASTER.show()
    sys.exit(app.exec_())
